<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends EntityRepository
{
    public function deleteEquipment(\AppBundle\Entity\Equipment $equipment) {
        $em= $this->_em;
        $equipment->setStatus(0);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($equipment);
            $em->flush();
            $em->getConnection()->commit();
            return $equipment;
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
    }


    public function saveEquipment(\AppBundle\Entity\Equipment $equipment) {
        $em= $this->_em;
        $equipment->setStatus(1);
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($equipment);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $equipment;
    }

    public function updateEquipment(\AppBundle\Entity\Equipment $equipment) {
        $em= $this->_em;
        $em->getConnection()->beginTransaction();
        try{
            $em->persist($equipment);
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            $em->close();
            throw $ex;
        }
        return $equipment;
    }
    public function getAll($offset = null, $limit = null, $search_query = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        if ($search_query) {
            $qb->andWhere(
                    $qb->expr()->orX(
                            $qb->expr()->like('lower(e.name)', ':search_query'), $qb->expr()->like('lower(e.searchData)', ':search_query')
            ));
            $search_query = strtolower($search_query);
            $qb->setParameter('search_query', '%' . strtolower($search_query) . '%');
        }
        $qb->orderBy('e.createDate', 'DESC');
        
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getAllBySite($offset = null, $limit = null, $site = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        
        if ($site && $site != "0") {
            $qb->join("e.site", 'u');
            $qb->andWhere('u.id = :site');
            $qb->setParameter("site", intval($site));
        }
        $qb->orderBy('e.createDate', 'DESC');
        
        if ($offset) {
            $qb->setFirstResult($offset);
        }
        if ($limit) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }
    
    public function getEquipmentBySite($site = null) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.status = 1');
        if ($site && $site != "0") {
            $qb->join("e.site", 'u');
            $qb->andWhere('u.id = :site');
            $qb->setParameter("site", intval($site));
        }
        try{
            return $qb->getQuery()->getResult();
        } catch(\Exception $ex){
            return null;
        }
    }
    
    public function getEquipmentQueryBuilder() {
         return $this
          ->createQueryBuilder('e')
          ->where('e.status = :status')
          ->andWhere('e.state = :state')
          ->orderBy('e.createDate', 'ASC')
          ->setParameter('status', 1)
         ->setParameter('state', 1);

    }
}
